# -*- coding: utf-8 -*-
"""Netflix Content Strategy Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqI4ztRNEXDWES16vOmYLYmO-jUuUqBz
"""

# 📦 Upload CSV from your local system
from google.colab import files
uploaded = files.upload()

# 📚 Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import io

# 🎨 Plotting settings
sns.set(style="whitegrid")
pd.set_option('display.max_columns', None)

# 🧾 Read the uploaded file (dynamic filename)
filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[filename]))
df.head()

# Clean column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Rename for readability
df.rename(columns={
    'available_globally?': 'available_globally',
    'release_date': 'release_date',
    'hours_viewed': 'hours_viewed',
    'language_indicator': 'language',
    'content_type': 'genre'  # Treating content type as proxy for genre
}, inplace=True)

# Convert date column
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')
df['year'] = df['release_date'].dt.year

# Convert genre column to str
df['genre'] = df['genre'].astype(str).str.strip()
df['language'] = df['language'].astype(str).str.strip()

# Genre trend plot over years
genre_trend = df.groupby(['year', 'genre']).size().unstack().fillna(0)

plt.figure(figsize=(18, 8))
genre_trend.plot(kind='area', stacked=True, colormap='tab20', figsize=(18, 8))
plt.title("🎬 Netflix Content Type Trends Over Time", fontsize=16)
plt.xlabel("Year")
plt.ylabel("Number of Titles Released")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# Most used languages in content
top_languages = df['language'].value_counts().head(10)

plt.figure(figsize=(12, 6))
sns.barplot(x=top_languages.values, y=top_languages.index, palette="viridis")
plt.title("🌍 Top 10 Languages in Netflix Content")
plt.xlabel("Number of Titles")
plt.ylabel("Language")
plt.show()

# Genre breakdown by language (e.g., English)
english_df = df[df['language'].str.lower() == 'english']
english_genre = english_df['genre'].value_counts().head(7)

plt.figure(figsize=(10, 5))
sns.barplot(x=english_genre.values, y=english_genre.index, palette="mako")
plt.title("🎬 Top Content Types in English-Language Netflix Content")
plt.xlabel("Number of Titles")
plt.ylabel("Content Type")
plt.show()

print("📌 RECOMMENDATIONS FOR VIEWER RETENTION:\n")

print("1. 📈 Invest more in content types that show consistent growth (e.g., Drama, Docuseries).")
print("2. 🌎 Expand multilingual content – top languages show strong demand (e.g., Spanish, Korean).")
print("3. 🎭 Blend popular genres (e.g., Crime + Documentary, Comedy + Romance) to increase variety.")
print("4. 📊 Leverage hours viewed + release date to schedule releases for peak interest periods.")
print("5. 📺 Encourage global content promotion by dubbing/subtitling high-performing regional shows.")